In [1]:
import pandas as pd
df = pd.read_csv(r'C:\Users\GEORGE TECHNOLOGY EN\Documents\data_jobs.csv')

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [4]:
df_salary = df[pd.notna(df['salary_year_avg'])].copy()


def projected_salary(salary):
    return salary * 1.03
df_salary['salary_infliated'] = df_salary['salary_year_avg'].apply(projected_salary)
df_salary[['salary_year_avg', 'salary_infliated']]

        salary_year_avg  salary_infliated
28             109500.0         112785.00
77             140000.0         144200.00
92             120000.0         123600.00
100            228222.0         235068.66
109             89000.0          91670.00
...                 ...               ...
785624         139216.0         143392.48
785641         150000.0         154500.00
785648         221875.0         228531.25
785682         157500.0         162225.00
785692         157500.0         162225.00

[22003 rows x 2 columns]

In [7]:
# this simple method 
df_salary['salary_infliated'] =  df_salary['salary_year_avg'] *1.03

In [8]:
df_salary[['salary_infliated', 'salary_year_avg']]

        salary_infliated  salary_year_avg
28             112785.00         109500.0
77             144200.00         140000.0
92             123600.00         120000.0
100            235068.66         228222.0
109             91670.00          89000.0
...                  ...              ...
785624         143392.48         139216.0
785641         154500.00         150000.0
785648         228531.25         221875.0
785682         162225.00         157500.0
785692         162225.00         157500.0

[22003 rows x 2 columns]

In [ ]:
# to turn the job_skill from a string to a list using the ast method 
import ast
ast.literal_eval(df['job_skills'][3])

list

In [17]:
def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(df['job_skills'][3])
df['job_skills'] = df['job_skills'].apply(clean_list)

Applying to a Row

In [22]:
def projected_salary(row):
    if 'Senior' in row['job_title_short']:
        return 1.03 * row['salary_year_avg']
    else:
        return 1.03 * row['salary_year_avg']
    

df_salary['salary_year_infliated'] = df_salary.apply(projected_salary, axis=1)

df_salary[['job_title_short', 'salary_year_avg', 'salary_year_infliated']]

       job_title_short  salary_year_avg  salary_year_infliated
28      Data Scientist         109500.0              112785.00
77       Data Engineer         140000.0              144200.00
92       Data Engineer         120000.0              123600.00
100     Data Scientist         228222.0              235068.66
109       Data Analyst          89000.0               91670.00
...                ...              ...                    ...
785624   Data Engineer         139216.0              143392.48
785641   Data Engineer         150000.0              154500.00
785648  Data Scientist         221875.0              228531.25
785682  Data Scientist         157500.0              162225.00
785692  Data Scientist         157500.0              162225.00

[22003 rows x 3 columns]